Description: >
    Deoga Kofi / Jenkins Servers
Parameters:
  EnvironmentName:
      Description: Single Parameter that we are passing with the env name.
      Type: String
Resources:
      JenkinsSecurityGroup:
          Type: AWS::EC2::SecurityGroup
          Properties:
            GroupDescription: enable all inbound traffic from port 80 and enable all outbound traffic to VpcCIDR
            GroupName: JenkinsSecurityGroup
            SecurityGroupIngress:
              - IpProtocol: tcp
                FromPort: 22
                ToPort: 22
                CidrIp: 881.156.228.212/32
              - IpProtocol: tcp
                FromPort: 8080
                ToPort: 8080
                CidrIp: 81.156.228.212/32
              - IpProtocol: tcp
                FromPort: 80
                ToPort: 80
                CidrIp: 81.156.228.212/32
            SecurityGroupEgress:
              - IpProtocol: tcp
                FromPort: 8080
                ToPort: 8080
                CidrIp: 0.0.0.0/0
              - IpProtocol: tcp
                FromPort: 80
                ToPort: 80
                CidrIp: 0.0.0.0/0

            Tags:
              - Key: Name
                Value: !Sub ${EnvironmentName} JenkinsSecurityGroup
            VpcId: vpc-c64106be
      JenkinsEc2Instance:
          DependsOn: JenkinsSecurityGroup
          Type: AWS::EC2::Instance
          Properties:
            ImageId: ami-0d1cd67c26f5fca19
            InstanceType: t2.micro
            KeyName: s2app
            SecurityGroupIds:
              - !Ref JenkinsSecurityGroup
            SubnetId: subnet-0db61550
            UserData:
              Fn::Base64: !Sub |
                #!/bin/bash
                apt-get update -y
                apt-get install openjdk-8-jdk -y
                apt-get install tidy -y
                wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
                sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
                apt-get update
                apt-get install -y jenkins
                systemctl start jenkins
                systemctl enable jenkins
                systemctl status jenkins
                systemctl restart jenkins
                apt install -y ansible
                apt install -y python-pip
                apt-get install apache2 -y
                systemctl start apache2.service
                mkdir -p nginx_ansible/roles/nginx/tasks


            Tags:
              - Key: Name
                Value: !Sub ${EnvironmentName} JenkinsEc2Instance

Outputs:
  JenkinsInstance:
      Description: Reference to the jenkins instance
      Value: !Ref JenkinsEc2Instance
      Export:
        Name: !Sub ${EnvironmentName}-JenkinsEc2Instance
